language: perl
sudo: false

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

script:
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" prove -r t

after_success:
  - cover -report coveralls

notifications:
  slack:
    secure: "ThlgunYz55cUHbvgPHyNDg4bdoC6/38ATBmksQvHGGuhQQ1E9ROQdwE1MfhzX51VPcA05qDVno8gzM6tDMQ4R9O7SykE24SBXV6DfyV9etP09IbFqc7z/przPNhqQ773rEWSWCvQiFIGIGGB4gFNkg1kUerGJ6Y/s4zZg+SZ0qQt8M4H1eBzhZgXnfj+jevcIIdTOlwd0msmdkRVyNJGpthBWO93t4IGE6wBWxzCuJHowOSDa40VV/QEaTX98/W3I1AsD+aSSTBTjp6D0vtfPGj0hLGkPtsGzmwkIo+IlMbZwfB3FzyzUOhXlYCBPe0yiQPqatNQc14JvY0O8rjdUVA5tKryCQDQ0wJLue6hEVQAy7xTYVnKhWXBv/cXS2YRuALHcq+uE1nXjbKzfjmq6vMe3k9fz5j4tpxJhuWmVfebaOF1mBrigLyrtCNntzd3PxOczYB3imKNXeUHvzKswodH1WqJP383DE9k6i08hZP0AppmjzA9K3A6esy9jlywdH8M9ZWtKJTGvE8nX25nQugIZiRUMup8o7kWdf+wPjtkgjuPmzsMDdR1IIn/z7hwn7F/BDk2I2O9yjpR9A+kEzoy7nk8ejBejjFpLXp6O+96my6GwMR9bRkazJ9xEeWe5eknkXjH7KueFdF6NoRVdrRQRgItsZKYDkIAhI4R+c4="
